added admincar to fix buy menu
Qbox-project/qbx_adminmenu pull request #27
Opened 2023-10-17 06:55 UTC by DevX32

## Description

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-10-17 06:57 UTC, DevX32 commented
need some changes i will do it soon

2023-10-18 03:12 UTC, DevX32 commented
need more changes wait for it

2023-10-18 15:55 UTC, Manason requested changes
Before working further on the implementation of this PR, we should discuss the merits of the idea of an admin car.

2023-10-18 16:15 UTC, DevX32 commented on server/main.lua
> +RegisterNetEvent('qb-admin:server:SaveCar', function(mods, vehicle, plate)
i will do all thing what u said

2023-10-18 16:26 UTC, DevX32 commented on server/commands.lua
> +    TriggerClientEvent('qb-admin:client:SaveCar', source)
its saves the car / give owership of veh/car

2023-10-22 01:22 UTC, closed without merging