refactor: standardized configuration
Qbox-project/qbx_adminmenu pull request #39
Opened 2024-01-20 20:00 UTC by MafewTM

## Description

Implement the standardized configuration

_accidentally closed my open pr for this_

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-07 18:46 UTC, solareon requested changes

2024-02-07 18:46 UTC, solareon commented on .vscode/settings.json
How did this get in here?

2024-02-11 19:09 UTC, solareon approved these changes

2024-02-11 22:50 UTC, BerkieBb approved these changes

2024-02-11 22:54 UTC, merged