refactor: lib locale
Qbox-project/qbx_adminmenu pull request #41
Opened 2024-02-01 01:18 UTC by skizmx

## Description

utilizing locale from ox

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-07 18:44 UTC, solareon requested changes

2024-02-07 18:44 UTC, solareon commented on locales/sv.json
Did this one get missed to be converted?

2024-02-07 21:31 UTC, solareon approved these changes

2024-02-11 18:25 UTC, MafewTM approved these changes

2024-02-11 18:26 UTC, merged